# -*- coding: utf-8 -*-
"""01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y_X90nAmiWgrfVpEeUerQRVd46w4_WHD
"""

import pandas as pd

data = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-06-01/summary.csv")

# Getting the time intervals
data[['premiered', 'ended','filming_started', 'filming_ended']] = data[['premiered', 'ended','filming_started', 'filming_ended']].astype('datetime64[ns]')
data["days_aired"] = data['ended'] - data['premiered'] 
data["days_filming"] = data['filming_ended'] - data['filming_started'] 

# Droping the original columns
cols_to_drop = data.loc[:,"premiered": "filming_ended"].columns
data.drop(labels = cols_to_drop, axis=1, inplace=True)
data.head()







pd.wide_to_long(data, stubnames="show_type", i="viewers_premier", j="total_views" )
# How to????

